### ISSUE TITLE
Store, manage, share and query location (history) data

### ISSUE THREAD

**Issue by pietercolpaert** [SolidLabResearch/Challenges#10]
## Pitch

Your location and its history is a valuable source of information for applications to offer you a more contextual user experience. 

You could for example 
 - share your current location (temporarily) with a friend without sending it to a different server
 - annotate your location history with the mode of transport you were using at that time, to analyse after a certain period your mobility behavior and whether using a different mode would’ve saved you time and money (cfr. https://savewithcarsharing.be/ - but then without manual data entry and with client-side query evaluation)
 - use your location history to check where a certain picture in your pod was taken
 - look-up when you were at a certain location in the past.

## Desired solution

 1. A background app for your smartphone that writes your location from the moment it changes to a Solid BasicContainer - may use the same configurable strategy as to store the chat history in #1 
 2. A domain model to store and annotate location history, cfr [the GPX ontology](https://github.com/linkeddata/gpx-ontology)
 3. [Linked Data Event Stream fragmentations ](https://tree.linkeddatafragments.org) to build indexes on top of your location history
 4. May contain time series summaries, to summarize a time window in one resource
 5. Needs a generic way to describe that a container or resource is a derived view of another

## Acceptance criteria

 - I want to be able to install an app or go to a webpage on my phone where I log in with my Web ID and indicate in which container I want to write my location history
 - I want to be able to build a Comunica query that gives me a fast response to 
     - where I was at a certain moment, 
     - when I was at a certain place, 
     - How much of the time is annotated with a specific graph pattern (e.g., to indicate I was traveling by train)
 - I want to be able to (temporarily) view the location of a friend on a map

**Comment by Sindhu-Vasireddy** [comment]
https://github.com/Sindhu-Vasireddy/LocationHistory

**Comment by pheyvaer** [comment]
@Sindhu-Vasireddy @pietercolpaert What is the status of this challenge?

**Comment by Sindhu-Vasireddy** [comment]
Status Update: https://github.com/Sindhu-Vasireddy/LocationHistory meets all the functionalities of the acceptance criteria with a basic UI. However we are yet to decide the best strategy for exposing the data on the pod, and also the best way to write to the pod that allows for efficient readability for which we have a brainstorming planned with @pietercolpaert and @woutslabbinck tomorrow at De Krook following our discussion from last week. 

Additionally the Job student who worked on this last month, added UI and the forked repository is available at https://github.com/tarikatac/LocationHistory, but the sharing functionalities are now broken when tested. This needs fixing to integrate with the original repository. Once we have the brainstorming strategy finalized will add an UI with the app working and update here.

**Comment by pheyvaer** [comment]
> https://github.com/Sindhu-Vasireddy/LocationHistory meets the functionalities of the acceptance criteria with a basic UI. 

Does that mean that we can check if this challenge is completed?

**Comment by Sindhu-Vasireddy** [comment]
The extent to which the application is the same as the demo I showed in Digital Vlaandren presentation two months back, after that I have not worked on this challenge, due to the ISWS summer school. Of the acceptance criteria 

> I want to be able to build a Comunica query that gives me a fast response to

>How much of the time is annotated with a specific graph pattern (e.g., to indicate I was traveling by train) 

was to be added by the job student last month, since the core functionality that enables it is available in the code and the app UI was to reflect it. However this is not working at the moment. So, once we have had today's meeting I can make further updates. 

> I want to be able to install an app or go to a webpage on my phone where I log in with my Web ID and indicate in which 
> container I want to write my location history

Also at the end of this meeting the way the app writes to the pod will be different from the current acceptance criteria. It will be stored in sessions, and a derived view will be used to read the data in an interoperable way across different apps. So there will be some major changes once we have a conclusive approach decided. 
The challenge cannot be closed unless the data written by the app can be read by other apps and vice versa.

**Comment by pietercolpaert** [comment]
Maybe I should rework the acceptance criteria here, so we can move the remaining work to a separate challenge to solve them generically. To be discussed in person later today.

Proposal for reworked acceptance criteria:
 *  I want to be able to install an app or go to a webpage on my phone where I log in with my Web ID and it writes my location history
 * A documented data model for location history
 * I want to be able to (temporarily) view the location of a friend on a map

**Comment by Sindhu-Vasireddy** [comment]
Update: [Location History](https://github.com/Sindhu-Vasireddy/LocationHistory) git repository has the app prototype that can be checked for the acceptance criteria along with the data model documentation. Additionally all data points are SHACL validated before being put on the pod.
The app is live on https://sindhu-vasireddy.github.io/LocationHistory/

**Comment by pheyvaer** [comment]
You find the report for this challenge [here](https://github.com/SolidLabResearch/Challenges/blob/main/reports/store-manage-share-and-query-location-history-data.md).
