### ISSUE TITLE
Using RFC-1149 for triple-based communication

### ISSUE THREAD

**Issue by j-steinbach** [SolidLabResearch/Challenges#101]
We live in a highly complex and multifarious world. To better facilitate the requirements of the modern age, interoperability between services is required.

RFC 1149 argues for the usage of avian carriers for IP transmission, as they provide high-delay, low throughput transmission in low-altitude metropolitan areas. Usage of RFC 1149 involves printing and wrapping the IP datagram around the legs of the avian carriers and then scanning them on reception. Avian carriers also have the benefit of automatic bug and worm detection and eradication and are especially useful in urban settings. Finally, avian carriers have a long TTL, allow for efficient caching and storage, and can be used in a decentral way.

The same approach could also be used for triple-based communication and Solid-based interconnectivity. Hereby one or more triples or pairs of triples or the respectively used ontologies are printed and attached to the carriers. Upon arrival, the delivered information needs to be scanned into a pod. This takes full advantage of the benefits of avian carriers and also improves interoperability and interconnectivity.

As RFC 1149 is still experimental, more tests and benchmarks have to be carried out. This post is intended to kick-start initial discussions.

Advanced questions:

- How does interoperability change with usage of different carriers (see also RFC 2549)?
- Security considerations of the long TTL
- Access-control considerations, especially with loss of carrier

Further reading:
- https://datatracker.ietf.org/doc/html/rfc1149
- https://datatracker.ietf.org/doc/html/rfc2549

**Comment by laurensdeb** [comment]
🐟🐟🐟

**Comment by pheyvaer** [comment]
@j-steinbach Can you please use the template for scenarios? Thanks!

**Comment by RubenVerborgh** [comment]
But is the proposal then that 3 carriers are sent out for each triple, to represent subject/predicate/object?
Not sure how that would work with blank nodes.

**Comment by j-steinbach** [comment]
Blank nodes could be represented with blank paper, to be identified by the carrier that carried the respective paper. But this likely has a throughput impact, as the same carrier would need to be used over and over. 

The need for three carriers brings also the issue of timing into perspective -- how do we make sure that the Subject arrives before the Object, with the Predicate message in between? This gets even more complicated when we take MITM or BOP (bird of prey) attacks and/or other possible losses of carrier.

Regarding the carriers themselves, based on the [Whats in a pod?](https://solidlabresearch.github.io/WhatsInAPod/) paper, they could be seen as living hybrid documents/resources themselves and might even be also stored in a pod -- I am not sure that the issue of living documents/resources and their storage in Pods has been solved yet.
