### ISSUE TITLE
Determining query equivalence between a newly registered query and an already executing query in the query registry.

### ISSUE THREAD

**Issue by argahsuknesib** [SolidLabResearch/Challenges#106]
## Pitch

This challenge is an extension of the solid lab challenge [84](https://github.com/solidLabResearch/challenges/issues/84). The [solid stream aggregator](https://github.com/argahsuknesib/solid-stream-aggregator) is a service that runs on top of a solid pod(s) to aggregate data streams stored in the solid pod. The data streams are generated from multiple sources to be stored in the solid pod using the [LDES in LDP](https://woutslabbinck.github.io/LDESinLDP/) specification. The user can register queries into the aggregator and generate a continuous materialized view over the streams stored in the solid pod. Moreover, multiple users can register the same to the aggregator. On registering the same query, the aggregator currently instantiates a new process to compute and develop a continuous view. However, such an approach is resource-consuming and hinders the scalability of the aggregator. Therefore, there is a need for the aggregator to determine if a newly registered query is similar to an already executing query, and if so, not register the query to compute. The Query Registry component of the aggregator keeps a record of the queries that are being executed currently and can be employed to identify query equivalence between a newly registered query and an already executing one. 

## Desired solution

The desired solution should be able to use the Query Registry component of the aggregator to determine the equivalence between an already-registered query with a newly registered one. 
As the queries have been registered in RSP-QL syntax in the query registry, the desired solution should be able to determine equivalence between RSP-QL queries.

## Acceptance criteria

The following functionality regarding evaluating the equivalence is required,
- between queries considering the query's stream and window parameters.
- considering the basic graph patterns of the queries involved.

## Scenarios

This is part of a larger [scenario](https://github.com/SolidLabResearch/Challenges/issues/16)

**Comment by argahsuknesib** [comment]
The [RDF Isomorphic](https://www.npmjs.com/package/rdf-isomorphic) package can be used to find isomorphism in the query's basic graph patterns.

**Comment by pheyvaer** [comment]
@pbonte Once you are doing with the review of the challenge, can you assign it to me? Thanks!

**Comment by argahsuknesib** [comment]
A first version of the rspql query equivalence package is developed [here](https://github.com/argahsuknesib/rspql-query-equivalence) finds if two RSPQL queries are equivalent. Improvements such as renaming the projection variable is to be made in the next steps.

**Comment by argahsuknesib** [comment]
The demo is finished with a repository containing instructions [here](https://github.com/argahsuknesib/query-equivalence-demo)

**Comment by pheyvaer** [comment]
Can you make sure that [all requirements](https://github.com/SolidLabResearch/Challenges/blob/main/how-to-manage-issues.md#requirements-before-requesting-completion-approval-of-challenge) are met? For example "You must provide a list of important technical decisions and assumptions that were made, such as the shape and the location of data." is not done.

**Comment by pheyvaer** [comment]
You find the report for this challenge [here](https://github.com/SolidLabResearch/Challenges/blob/main/reports/determining-query-equivalence-between-newly-registered-query-and-already-executing-query.md).
