### ISSUE TITLE
Solid reasoning proof checking 

### ISSUE THREAD

**Issue by josd** [SolidLabResearch/Challenges#21]
The Solid reasoning answers can be trusted via an independ proof checker.

## Actors/actresses 
A proof generator and an independent proof checker.

## Preconditions
Solid reasoning data, rules and query availabe on the web.

## Steps
- Get the Solid reasoning data, rules and query
- Generate the proof with the the proof generator
- Check the proof with the independent proof checker
- Generate a report of the proof check

## Postconditions
The proof is checked and a report is generated.

**Comment by josd** [comment]
There is a working test scenario at https://github.com/josd/eye/tree/master/reasoning/socrates and another one at https://github.com/josd/eye/tree/master/reasoning/witch

**Comment by josd** [comment]
This is deductive reasoning as explained in https://www.w3.org/DesignIssues/Semantic.html

**Comment by pheyvaer** [comment]
@RubenVerborgh What changes would you like to see here?

**Comment by RubenVerborgh** [comment]
I would need a concrete use case. I understand that a proof checker is generic, but we should set a concrete goal for a proof that we should be able to check.

**Comment by josd** [comment]
Could be something similar to https://www.w3.org/2006/09dc-aus/swpf#(3)

-- https://josd.github.io

**Comment by pheyvaer** [comment]
@josd Can you add a concrete goal as Ruben mentions?

**Comment by josd** [comment]
So this was intended as a scenario https://github.com/SolidLabResearch/Challenges/issues/21#issue-1184819705 and not as a concrete use case. Proof checking could be applied for https://github.com/SolidLabResearch/Challenges/issues/58
