### ISSUE TITLE
Automatically test the performance of each CSS commit

### ISSUE THREAD

**Issue by wvdemeer** [SolidLabResearch/Challenges#23]
## Pitch

Changes to CSS can have an impact on the memory, CPU and even bandwidth usage of the CSS. 
It would be nice to know this impact for each commit to the CSS repo, in order to spot performance impact as soon as possible.

## Desired solution

For each commit to the CSS repo, a [github push webhook](https://docs.github.com/en/developers/webhooks-and-events/webhooks) will notify a solidlab server. This server will run one or more "performance tests". These tests should evaluate realistic usage scenarios. When the tests are done, the results are reported back to the CSS repo as [commit statuses](https://docs.github.com/en/rest/reference/commits#commit-statuses). These commit status contain link to a full test report. Typically this status will be "success", but if there is a (significant) negative performance impact, the status should be "failed".

## Acceptance criteria

For each commit to the CSS repo, a commit status that links to a performance report should pop up.

**Comment by jeswr** [comment]
Related discussion for upstream packages https://github.com/RubenVerborgh/AsyncIterator/issues/62 - could possibly be implemented simultaneously?

**Comment by pheyvaer** [comment]
@RubenVerborgh What are the changes that you would like to see here?

**Comment by RubenVerborgh** [comment]
@pheyvaer I actually revised this again, and we're good to go.

**Comment by pheyvaer** [comment]
@RubenVerborgh Ok, great!
@wvdemeer Seeing that you are assigned to this, are you working on this at the moment?

**Comment by wvdemeer** [comment]
Currently I'm caught up in some other stuff, but I'm itching to get back into this soon.

A lot of work was done already, a lot of the sub parts required for this actually already work now. The big todo now, is to make it easily configurable and usable by anyone but me. I know how I'm going to do that, it's now "just a matter of writing the code" ;-)

**Comment by pheyvaer** [comment]
@wvdemeer Can you provide a small update here of the status of the platform you are working on?

**Comment by wvdemeer** [comment]
Current status: The testing platform can now run a first decent test, process the data and show the results. It can run multiple of these tests safely, and it can handle most of the minor error cases that can occurs along the way.

Next Steps: Improving and expanding the tests that run, to make sure the results are valid and valuable, and thus that we're testing relevant things.
After that, we'll focus on making the entire thing usable by others.

**Comment by pheyvaer** [comment]
Should we create a separate challenge for the "make the entire thing usable by others"? @RubenVerborgh What do you think?

**Comment by RubenVerborgh** [comment]
Yeah, let's scope challenges as narrowly as possible!

**Comment by pheyvaer** [comment]
@wvdemeer Can you move the "make the entire thing usable by others" to a new challenge and update the current one to remove that part? Thanks!

**Comment by wvdemeer** [comment]
Ok, done in #81 (didn't change this issue, this part of it was not mentioned.)

**Comment by wvdemeer** [comment]
Current status: The tests that runs are being improved and expanded, including tests of CSS with and without authentication. The aggregation of the data from the test has improved.

Next step: Continue improving and adding tests, making sure the results are valid and relevant CSS development. (+ Debugging and improving the platform along the way.)

**Comment by wvdemeer** [comment]
Current status: There are some interesting (but preliminary) results, related to authentication and multi-threading.

These results will be investigated and debugged further, and will be discussed further once we're sure enough they show CSS performance and not performance test bugs.

In a meeting this morning it was also mentioned it would be nice to finish this challenge by the end of this year. That should be possible, so that's a good goal!
(Just to be clear: Finishing this challenge means a first decent version, not "the ultimate version". Improvements will off course continue to be made after this first version.)

**Comment by RubenVerborgh** [comment]
Excellent, thanks a bunch @wvdemeer and team.

**Comment by pheyvaer** [comment]
You find the report for this challenge [here](https://github.com/SolidLabResearch/Challenges/blob/main/reports/automatically-test-performance-of-each-css-commit.md).
