### ISSUE TITLE
Add object store backend to further enable scalable cloud deployments

### ISSUE THREAD

**Issue by MisterTimn** [SolidLabResearch/Challenges#26]
## Pitch
Object storage is a go to storage backend in many cloud based use cases. Cloud providers such as AWS and GKE offer scalable and affordable object storage options. CSS should have an optional Object Storage backend so cloud deployments are made easy and effective. Also with regard to scalability, Object storage has an upper hand compared to other storage forms like file or block.

## Desired solution

- Build out the object storage backend (using self deployed [MinIO ](https://docs.min.io/minio/baremetal/index.html ) and later moving to [S3](https://aws.amazon.com/s3/) for instance)
- Maximize the usage of Object Storage, as it is very unrestrictive and optimizable (no hierarchy, full control of metadata).

## Acceptance criteria
- CSS can use MinIO and/or other S3 compliant Object Stores
- CSS can be deployed on AWS and use S3 Storage
- CSS can be deployed on GKE and use Google Object Storage
- Installation instructions for these use-cases are provided (through e.g. Helm chart, shell scripts, etc.)

**Comment by pheyvaer** [comment]
@RubenVerborgh What changes do you expect here?

**Comment by pheyvaer** [comment]
@MisterTimn Did you have the chance to look into making the necessary changes?

**Comment by MisterTimn** [comment]
Not yet, will have to take some time to further investigate and experiment with it before I can properly define a concrete use case and demo

**Comment by pheyvaer** [comment]
@MisterTimn I want to check in to see if you already had the chance to further investigate.

**Comment by MisterTimn** [comment]
No and probably won't be able to any time soon... should I just close the challenge for now?
