### ISSUE TITLE
Determine permissions for resource

### ISSUE THREAD

**Issue by pheyvaer** [SolidLabResearch/Challenges#40]
## Pitch

- Allow developers to determine whether the logged-in user can read/write/control a resource.

## Desired solution
- This is part of the SDK.
- Functions along the lines of
  - `canWriteToResource(resource)`
  - `canReadResource(resource)`
  - `canControlResource(resource)`

## Acceptance criteria

- I want a JavaScript example.
- The different permissions are listed for resources where the logged-in user has read, read/write, write, and control permissions.

## Pointers
I did the following in an app:

```js
async function canWriteToResource(resource, solidFetch) {
  const response = await solidFetch(resource,
    {
      method: 'HEAD'
    });

  const header = response.headers.get('wac-allow');

  if (header) {
    return header.includes('write');
  }

  return false;
}
```

**Comment by RubenVerborgh** [comment]
https://solidproject.org/TR/wac#wac-allow ?

**Comment by pheyvaer** [comment]
Sweet! This works for me.
