### ISSUE TITLE
Browser extension intercepting urls to open notification with a user defined app

### ISSUE THREAD

**Issue by phochste** [SolidLabResearch/Challenges#45]
In a decentralized Solid world many applications will provide functionality to do one or more specialised actions, such as browsing files, playing games, creating a Doodle, participating in a Quiz. In this environment users have a preference for apps they want to use to do some tasks:

- When the user wants to browse a pod , she wants to use App X
- When the user wants to play chess she wants to use App Y
- When the user wants to edit a text resource she wants to use App Z

This challenge is specific for solving "what to App to use when reading Solid pod `inbox` notifications". 

- The user visits the inbox of a Pod
- The browser extension intercept notification URLs 
- Based on the notification resources it finds it can find out the type of notification (e.g. a chess notification, an invite notification, a quiz notification)
- The user has a preference of Apps to open for a type of resource:
     - For a chess notification: open the Chess App
     - For an invite notification: open the Doodle App
     - For a quiz notfication: open the Quiz App
     
![IMG_0706](https://user-images.githubusercontent.com/66416/173520378-d88f7f96-2185-4f7d-a719-e4faa4c6d086.JPG)

## Actors/actresses 

- User of the application
- Browser extension

## Preconditions

- User has launched the extension
- User has a configuration menu to map URLs / Resource types to an application
- User can set a scanning base (e.g. based on a regex):
     -  `scan =~ /inbox/ ` 
- User can e.g. set a regex rule:
     -  `type =~ /Chess/` : `http://mychess.app/?url={url}`

Advanced functions implementations might consider creating (N3) rules to decide what app to open based on resources/types. In combination with well known resources (e.g. scan `inbox:` when it is known from the user profile where in the inbox is) 

## Steps

- The user browses the (Solid) web
- At some point in time, the user visits a webpage that matches the "scanning base" that was set in the browser extension
- The user clicks on a notification message 
- The browser plugin will intercept opening of URLs in this scanning base (based on the rules defined above) and open the preferred application for a URL. This mimics a way how a preferred email program is opened when a URL with a `mailto:` scheme is found.
- The browser plugin will fill in the URL stup and open the preferred Solid App

## Postconditions

- The notification is opened in the preferred Solid app based on the configured type.

**Comment by phochste** [comment]
Related to https://github.com/SolidLabResearch/Challenges/issues/44

**Comment by pheyvaer** [comment]
What do the first two steps mean? They are not clear to me.

**Comment by phochste** [comment]
@pheyvaer I've updates the text. Is it now better?

**Comment by pheyvaer** [comment]
Yes!

**Comment by phochste** [comment]
The [AcmePlugin](https://github.com/phochste/AcmePlugin) is a new Chrome extension that can be used to add a configurable dynamic context menu to every link, image, page. The context menu can be configured using a template e.g.

```
Open... = 
https://solideditor.patrickhochstenbach.net/?resource={resource}
```

This will open the current URL in context in the [SolidEditor](https://solideditor.patrickhochstenbach.net) app. 

Solid Apps that want to have this support need:

- A way to transport a resource URL as query parameter
- Have a nice way do a (re)login when the user follows this link

**Comment by phochste** [comment]
![Screenshot 2022-06-25 at 20 46 28](https://user-images.githubusercontent.com/66416/175786643-ea4ef629-386f-4c42-96c3-b4d1df592489.png)

**Comment by phochste** [comment]
The latest version of AcmePlugin support setting wildcards on which URLs one would like to see a context menu.

**Comment by RubenVerborgh** [comment]
Excellent job, this is great 👍

**Comment by pheyvaer** [comment]
You find the report for this challenge [here](https://github.com/SolidLabResearch/Challenges/blob/main/reports/browser-extension-intercepting-urls-to-open-resources-with-user-defined-app.md).
