### ISSUE TITLE
External service stores calendar in pod

### ISSUE THREAD

**Issue by pheyvaer** [SolidLabResearch/Challenges#68]
## Pitch

At the moment it's possible to request a calendar from a CSS instance through the use of a [store](https://github.com/KNowledgeOnWebScale/solid-calendar-store/). But this solution is coupled to the implementation of CSS. A better solution would be to have an external service that reads the original calendar and stores it in a pod using only the methods specified by Solid.

## Desired solution

This can be a CLI tool that is executed periodically with a cron job on a server. Let's make this as lightweight as possible. Thus, do not use unnecessary frameworks for this. 

## Acceptance criteria

- I install a service on a server, which can be different from the server that is running my pod.
- I configure the service to read data from my ICS feed. 
- I configure the service to write the data to a specific resource on my pod.
- I configure how often the calendar data is updated on the pod.
- I log in with my WebID in the service so that it can write to private resources.
- The service supports [these manipulations](https://github.com/KNowledgeOnWebScale/solid-calendar-store/blob/master/docs/stores.md).

## Pointers
- https://communitysolidserver.github.io/CommunitySolidServer/5.x/usage/client-credentials/
- You should be able to reuse parts of the code of [this store](https://github.com/KNowledgeOnWebScale/solid-calendar-store/).

## Scenarios
- https://github.com/SolidLabResearch/Challenges/issues/2

**Comment by RubenVerborgh** [comment]
More specifically, can we develop a universal technique (applied to the calendar use case) such that the 3 situations below can be implemented with the same code?
- the calendar is a backend store to the pod
- the calendar is an agent that writes to the pod (optimization: possibly via a read hook)
- the calendar is an agent that has its own store; the pod replies by linking to it

@pietercolpaert has a single diagram that can be interpreted as the above 3 cases.

**Comment by jeswr** [comment]
FWIW I don't see the read hook as just an optimisation in the second case. It is necessary to guarantee consistency between to pod and the calendar whenever an app reads from the pod.

**Comment by RubenVerborgh** [comment]
> I don't see the read hook as just an optimisation in the second case

Ack. With "an agent that writes to the pod", I meant to say "an agent that writes to the pod _every time there is a change in the backend_". So if my calendar changes 1000 times, but there is only 1 read in that period, there would still be 1000 writes, 999 of which would be unnecessary. So there, read hooks are a bandwidth optimization.

However, that does not account for cases where there is no defined update frequency or notification. I've adjusted the language above

**Comment by pheyvaer** [comment]
@RubenVerborgh Yes, it makes sense to look at other techniques and ideally it can be done with the same code, but for the sake of keeping challenge concise and solvable within 2-3 months I would stick to only one technique: "the calendar is an agent that writes to the pod". The other two techniques and optimizations are then put into separate challenges. What do you think?

**Comment by RubenVerborgh** [comment]
Well, the objective should really be to find 1 method that works for all cases. I'm fine with this challenge only addressing 1 case, but the solution should be generic or it doesn't make sense to pursue it.

**Comment by pheyvaer** [comment]
Sure, the fact that we use calendar data should be confined to only one part of the code and the rest of the code should ideally be readily available to be reused for other data as well.

**Comment by bjdmeest** [comment]
Adding pointers:

- https://github.com/sevrijss/long_term_auth
- https://github.com/SolidLabResearch/Bashlib

**Comment by pheyvaer** [comment]
@RubenVerborgh Are changes still needed here?

**Comment by RubenVerborgh** [comment]
Okay for me if the method is portable to other cases.

**Comment by zimengzhou1** [comment]
@pheyvaer

**Comment by renyuneyun** [comment]
Comment as required to allow mentioning me :)

**Comment by pheyvaer** [comment]
The code that @zimengzhou1 and @renyuneyun created is [here](https://github.com/renyuneyun/calendar-orchestrator), specifically in the folder `core`.

**Comment by pheyvaer** [comment]
You find the report for this challenge [here](https://github.com/SolidLabResearch/Challenges/blob/main/reports/external-service-stores-calendar-in-pod.md).
