### ISSUE TITLE
Public CSS instance for testing

### ISSUE THREAD

**Issue by pheyvaer** [SolidLabResearch/Challenges#75]
## Pitch
It would be great to have a public CSS instance that can be used for testing. That way developers can quickly make an account to test or demo an application.

## Desired solution
- A public CSS instance.
- Everyone can make an account.
- The instance is reset every 24 hours.
- The instance is initiated, after the reset, with a predefined set of accounts.

## Acceptance criteria
- I can access the CSS instance from the public Internet.
- I can create a new account.
- The CSS instance is reset every 24 hours.
- I can define a set of accounts that are automatically created in the instance after the reset.
- I can define the data that is preloaded for these accounts.

**Comment by Dexagod** [comment]
Can we make this instance use the mashlib preset? I think this will be necessary for peope to see what is happening on the pod itself when developing.

**Comment by pheyvaer** [comment]
@Dexagod What is the "mashlib preset"?

**Comment by joachimvh** [comment]
Configured so it has the mashlib frontend: https://github.com/CommunitySolidServer/Recipes

Would also have to establish what kind of configuration you want for this server due to the different options. E.g., (once it is merged) do you want WebACL or ACP?

**Comment by pheyvaer** [comment]
Thanks for the link! Regarding things like WebACL and ACP, we have multiple instances with different options and then people can pick what they want.

**Comment by Dexagod** [comment]
I'd also try to include stuff like inbox + links, type indexes, ... as default in the template for the pods.
I would like such a preset for when I have webdev course so students can work with these things without having to set them up themselves.

**Comment by pheyvaer** [comment]
@Dexagod Make sense. We can have a default pod for each group in the course then for example. This challenge should allow us to configure this easily.

**Comment by RubenVerborgh** [comment]
Or maybe choose to _not_ have Mashlib actually; so people get used to the decoupled view (and get to distinguish between what is Mashlib and what is Solid).

Because it is possible to use it as an external app: https://solidos.github.io/mashlib/dist/browse.html?uri=https%3A%2F%2Fdrive.verborgh.org%2F

Side-note: we need to have a Mashlib alternative, perhaps if we just patch up Penny. In the good old days, there used to be Warp, which was just a filebrowser, but that was actually very handy.

**Comment by twalcari** [comment]
A CSS instance is now live on https://pod.playground.solidlab.be/ . It resets every night at 5AM.

It is seeded by the following file:
```
[
  {
    "podName": "user1",
    "email": "user1@pod.playground.solidlab.be",
    "password": "user1"
  },
  ...
  {
    "podName": "user10",
    "email": "user10@pod.playground.solidlab.be",
    "password": "user10"
  }
]
```

**Comment by RubenVerborgh** [comment]
That is absolutely great, @twalcari! Thanks!

Does @pheyvaer know how to change the seed file?

**Comment by pheyvaer** [comment]
You find the report of this challenge [here](https://github.com/SolidLabResearch/Challenges/blob/main/reports/public-css-instance-for-testing.md).
