### ISSUE TITLE
Edit Pod files in vscode

### ISSUE THREAD

**Issue by jeswr** [SolidLabResearch/Challenges#80]
## Pitch

The goal of this challenge is to create a vscode extension similar to [remote ssh](https://code.visualstudio.com/docs/remote/ssh) that allows you to edit files on a remote POD as if they were directly on your machine - thus removing the barrier of entry to enabling devs and admins to inspect Pods both for their own understanding of what is there for the own Pedagological gain - and also allowing them to edit data in Pods. 

## Desired solution

The desired solution would being able to follow the following workflow:
 - Press `ctrl`+`shift`+`p` to open the command panel, search `remote-solid` and press enter to start up the selection.
  - The command panel should ask for a Pod host URL which you fill in and press enter.
  - The browser should open with a log in to the relevant Pod provider
  - Once Logged in you should be redirected back to vscode with the file tree at the left at the root of your Pod. You should be able to read all files you have read access to; and modify all files you have write access to. You should also be able to create new file as your permissions enable.

## Acceptance criteria

See desired solution. The file tree visualisation is not required, instead you could implement the same functionality of searching paths as `remote-ssh`.

This should work when tested against at least one CSS and one ESS instance. I would suggest it should work against the following deployments:
 - [Inrupt Pod Spaces](https://start.inrupt.com/profile)
 - [SolidLab Playground](https://pod.playground.solidlab.be/)

## Pointers

 - https://code.visualstudio.com/docs/remote/ssh (remote ssh); the source code is https://github.com/microsoft/vscode-remote-release
 - https://marketplace.visualstudio.com/items?itemName=Elsevier.linked-data (linting, probably should not be part of this extension though)

**Comment by jeswr** [comment]
Really wanted this, spent a few hrs on it yesterday. Almost done barring a critical bug around sessions.

**Comment by RubenVerborgh** [comment]
- @Dexagod's https://github.com/SolidLabResearch/Bashlib might help
- We could also mount the Solid Protocol to the filesystem.

**Comment by Dexagod** [comment]
I might be able to make something like this work indeed with the bashlib code.
Currently it already supports the editing of files bij moving it to a /temp folder.
(Though this would need it to be a bit more robust, handle timeouts, re-logging in, etc...)

Although i feel like to make this optimal, supporting the mounting of a solid pod locally would be ideal? Or would that be overkill?

**Comment by jeswr** [comment]
> Or would that be overkill?

In the case of VScode probably overkill. It has most of the functionality to handle virtual file systems built in and all we need to do is implement the `vscode.FileSystemProvider` interface (see https://github.com/microsoft/vscode-extension-samples/blob/main/fsprovider-sample/src/fileSystemProvider.ts).

I have this working - the primary bug that I was running into is that the authentication session was not persisted between extension activations so I just needed to make sure that the session information was stored in the `vscode.ExtensionContext` in a way that is recoverable. I have mostly implemented this.

**Comment by Dexagod** [comment]
You can store the session information and reuse it (i do this with bashlib)
Though it's a bit hacky a.t.m.

If you work with Community Solid Server, you can work with Client credentials tokens, and then you don't need to worry about session management that much, as you don't need to do the interactive login step anymore (Inrupt also has some kind of support for this, but that's only for applications these tokens and not for users AFAIK)

**Comment by jeswr** [comment]
Draft version available https://marketplace.visualstudio.com/items?itemName=jeswr.solidfs

**Comment by pheyvaer** [comment]
@jeswr Do you also have a link to the code of the draft version?

**Comment by pheyvaer** [comment]
You find the report for this challenge [here](https://github.com/SolidLabResearch/Challenges/blob/main/reports/edit-pod-files-in-vs-code.md).
